version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: csvbot-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
    container_name: csvbot-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
